[quote.epigraph, , Rom. 8:18]
____
For I reckon that the sufferings of this present time are not worthy to be
compared with the glory which shall be revealed in us.
____

== Preface

Perhaps little more need be said on behalf of the following pages,
than that they exhibit a lively specimen of the patience, meekness, humility,
and Christian zeal which abounded in the Society
of Friends at the time of its early existence.

In the character of William Bennit, from whose writings this little compilation is taken,
these fruits of the Spirit appear to have been very conspicuous.

The first part of the Memoir is taken from a piece in his works,
entitled,
The Work and Mercy of God Conducing to His Praise,
or a Demonstration of the Visitation of God`'s Love to My Soul in the Days of My Youth;
the remaining part is extracted from testimonies concerning William Bennit,
written by two of his friends and fellow-sufferers for the truth: and although,
for the sake of brevity, some parts of these, and also of the other pieces,
as they stand in the original publication, dated 1685, are omitted,
yet it is believed that these Selections will not, on that account,
prove the less instructive; and that the abridged form in which they are now offered,
will obtain for them a more extensive circulation.

T+++.+++ C.

Kingston on Thames.
