== Chapter VI. A Letter to a Friend Under Suffering

Dear Friend,

In that which is eternal and unchangeable,
doth the salutation of my soul extend towards thee.
+++[+++I am]
in some measure sensible of the many troubles and crosses which thou hast been under,
and art now exercised with; and truly, dear heart,
my soul desireth that the Lord may enable thee to wade through them all,
in the pure patience and true contentedness;
and that thou mayst find the arm of his mighty power,
beating down and keeping under that part, which would complain and murmur against Him;
which would fret itself because the wicked flourish,
and the proud lord it over the meek of the earth.
I say, needful it is to know that part, which would fret itself because of these things,
chained down by the lowly, lamb-like Spirit of +++[+++the Son of]
God.
This Spirit keeps in coolness, gentleness, and patience; enables to love enemies;
makes willing to leave all to the Lord, and gives dominion over that spirit,
which in haste, yet, as it thinks, in a zeal for God,
cries for fire to come down from heaven,
to devour those who are instruments of cruelty and oppression.

Unto the Lord, dear heart, let us commit our cause; and sure I am, he will plead it,
in his own time, to our joy and comfort in the end.
Meanwhile, the Lord keep us in contentedness,
and in dominion over that spirit which counteth the Lord slack concerning his promise;
for indeed, "`He is not slack, as some men count slackness,
but is long-suffering to us-ward; not willing that any should perish,
but that all should come to repentance.`"
My dear friend, my soul fervently desires, that thou and I,
with the rest of our heavenly Father`'s family,
may be kept close unto the measure of the free grace and love of God in our own hearts;
that by it we may be continually preserved in the lowly fear and pure awe of Him.
Herein let us watch carefully over our thoughts, words, and works,
lest in haste we should speak or do any thing that may grieve the holy seed,
wound the just one in ourselves, and bring a burden upon our own souls.

Wherefore, dear heart, I cannot but desire, that I, with thee,
and all who love righteousness, may be kept watchful in the lowly fear,
close unto the grace that keeps humble, and in the fewness of words;
that so in sweet stillness and peace we may possess our souls,
and enjoy the incomes of the love +++[+++of God,]
the pure refreshing streams of the fountain of life, according to our measures; and that,
even in the midst of our trials and sufferings, our hearts may be made glad in the Lord,
and our souls may rejoice in him over all the rage and cruelty of the wicked.

So, dear heart, I leave thee unto the Lord, in whom my love is to thee;
my soul sympathizes with thee in thy trials and sufferings,
and desires the Lord may bear thee up above them all,
in the bosom of his love and patience; +++[+++may He]
minister daily unto thee, what He knoweth is meet for thee,
and so keep thee in contentedness with his heavenly will, +++[+++as]
that thou mayst say with thy whole heart, "`Lord, not my will, but thine be done.`"

In that love which drew me forth to write these lines unto thee,
I remain thy dear friend in the truth.

William Bennit

1665.
