== Chapter VII. Some Prison Meditations of an Humble Heart

Oh, my soul, be not unmindful of the large mercy and goodness of the Lord,
showed towards thee.
Let the sense of what thy compassionate God hath done for thee,
be continually fresh in and upon thee;
for he hath freely done that for thee which none besides him, the Mighty One, could do.
He hath brought thee out of the horrible pit, and out of the mire and clay,
hath set thy feet upon a rock which can never be moved,
and thereon establisheth thy goings; praises, living praises,
be rendered to the Lord thy God forever and forevermore.
Remember, oh, my soul, thou wast once like a poor silly sheep without a shepherd,
wandering upon the barren mountains,
the dry heaths in the wilderness and solitary places, full of trouble and perplexity,
not knowing the way to the fold of rest, oftentimes mourning and weeping alone,
as a dove without her mate; and no eye saw thy sorrow but the Lord alone.
When thou didst eat thy bread with weeping, and mingled thy drink with tears,
he the compassionate One, heard thy secret cries, and knew thy desires;
thy sighing and groaning entered into his ears; +++[+++He]
was moved with pity towards thee, delivered thee out of distress,
freely reached forth his arm, brought thee out of the wilderness,
and set thy feet in the way which hath led thee to the fold of rest.

Now, oh, my soul, he is become thy Shepherd; he oftentimes feedeth thee,
causeth thee to lie down in green pastures, leadeth thee by the still waters,
even Shiloh`'s brook, which runs softly;
spreadeth thy table in the sight of thine enemies,
anointeth thine head with the oil of gladness, causeth thy cup to overflow with new wine,
and hath brought thee to sit under thy own vine and fig-tree, +++[+++where]
none shall make thee afraid.
The goodness and mercy of the Lord is unutterable, unfathomable, and incomprehensible!
Oh, the height, the depth, the length, and breadth of his love!
When thou meditatest thereon, oh, my soul,
and considerest his lovingkindness towards thee,
how can the sense thereof but pitch thee even upon a stand of admiration.
Surely, when thou lookest back into his works,
and considerest how much he hath wrought in thee, thou canst see no end of his praises;
living praises to the holy righteous Lord God, be ascribed by thee, oh, my soul,
forever and forevermore.

As thou art kept in the fresh sense and remembrance of the great mercy and unspeakable
compassion which the Lord thy God daily manifests unto thee,
how canst thou but abound in love, in pity, in tenderness,
and compassion towards all people;
but especially towards those who are hungering and thirsting after righteousness,
after everlasting rest and happiness.
When joy hath come into +++[+++thee,]
oh, my soul, as a river, and gladness as a mighty stream,
refreshings as showers in the spring, and consolation as dew upon the tender plants;
when thou couldst shout praises and hallelujahs to thy God,
even then thou rememberedst the poor and needy,
and thoughtst thou heardst his cry sounding in thy ears, "`Oh,
whose condition is like mine?
Is there any so poor, so weak, so foolish, so desolate as I? Oh, my leanness,
my leanness! how long shall it be thus with me?
How long shall my beloved be hid from me, as in the clefts of the rocks,
and as in the secret places of the stairs?
When shall I have a full enjoyment of him?
Where shall I find one who is sensible of my condition, that can sympathize with me,
and that can speak a word in season unto my poor soul!
Oh, is it thus with any as it is with me?`"

Yes, yes, I believe there are many who have been, and now are in thy condition.
For though I am indeed but a child,
yet truly I am in some measure sensible of thy condition, and can read it by my own;
and willingly would I help thee according to my ability.
Oh, methinks I would be a help to all who stand in need of help,
but especially unto thee, thou poor soul.
What! art thou poor?
So am I. Dost thou eat thy bread weeping, and mingle thy drink with thy tears?
It is so with me when I want the enjoyment of him whom my soul loveth.
Sometimes my beloved seems to be withdrawn; oh, then sorrows take hold on me,
mourning covereth me as a garment, and none seeth my tears but the Lord;
they are my meat and drink, whilst my enemy saith unto me, "`Where is thy God?
Dost thou think he will ever appear again unto thee?
Why dost thou hunger, thirst, cry and pant after him?
Alas! it is in vain for thee to wait for him.
Once indeed thou hadst the enjoyment of him;
once thou wentest with the multitude to the house of God,
with the voice of joy and praise, with a multitude that keep holyday;
but thou must not look for such a day again.`"
Thus the adversary of my soul endeavoureth to add sorrow to my sorrow,
and to increase the weight of my burden, that so I might sink and never rise.

But the Lord my God is near to help me,
even in the time when I can scarcely perceive him;
and when I am (as Peter was) ready to sink,
then his invisible arm of mercy is ready to save me;
and a secret hope he preserveth alive in me, that he will appear again to my joy.
Hereby some encouragement I feel stirring in me, to wait upon the Lord patiently,
and to trust in him, though I do not see him.
Surely, oh, my soul, he will appear again to thy joy,
for thou canst not be satisfied without his presence; the Lord seeing it is so with thee,
that thou desirest his presence more than all other things,
surely will not cast thee off forever, but will appear again to thy joy.
+++[+++Then]
why art thou so much cast down, oh, my soul, and why art thou thus disquieted within me?
Oh, hope thou in thy God, for thou shalt yet praise him;
the Lord will yet command his lovingkindness in the daytime,
and in the night season his song shall be with thee, even praises to the God of thy life.

Oh, wait patiently upon the Lord; his compassions fail not towards those who love him.
He will send forth his light and his truth into thee again:
it shall bring thee to his holy hill, and to his tabernacle;
then shalt thou go to the altar of God, unto God thy exceeding joy.
It is good for thee both to hope and quietly wait upon the Lord;
for "`the Lord is good to them that wait for him, to the soul that seeketh him.`"
Oh, wait patiently upon him, even as the husbandman, who soweth his seed in the earth,
hath long patience for it, until he receive the early and the latter rain.
He who is to come will come, and will not tarry, and his reward will be with him,
even fulness of joy, comfort, peace, rest, and sweet satisfaction.
Surely the Lord will never leave thee, if thou forsake not him.
He may indeed seem to hide his face from thee for a time:
but without doubt he will appear again to thy comfort.

Oh, my soul, the Lord often heareth thee saying in secret,
"`What is the glory of the world to me?
What are the favours, friendship, and estimation of the world to me?
What are the vanities and pleasures of the sons and daughters of men to me?
Surely all these things are but as dross and dung to me,
in comparison of the Lord my God, the fountain of everlasting joy and pleasure.
Oh, if I enjoy him fully, I have enough; he is the joy of my heart,
the rejoicing of my spirit, the strength of my reins, the girdle of my loins;
wherefore how can I live without him?`"
Oh, my soul, the Lord intends good unto thee by all his dealings with thee.
If he hide his face from thee for a season, it is to let thee see how poor, weak,
foolish, dry, and unfruitful thou art without him;
that so thou being made to feel thy own weakness and inability,
mayst be the more sensible of the need of his supporting power and saving grace,
and rely the more upon him.

+++[+++Thus]
thou learnest to prize the sweet enjoyment of his presence, to cleave unto him,
to be very careful thou dost not grieve him,
nor do anything that may cause him to withdraw himself from thee.
Oh, my soul, thou must know how to want and how to abound; how to be full,
and how to be empty; how to be rich, and how to be poor;
and in every condition to be content.
The Lord can open, and none can shut; and he can shut and none can open.
He can open the windows of heaven, and shower down abundantly upon thee.
He can even make a plenty in thy land, cause thy store to abound with corn,
and thy fats to overflow with new wine.
He can also shut up the windows of heaven for a time, and make a famine in thy land;
and thou must not say to him (in a murmuring way,) "`Why dealest thou thus with me?`"
For indeed he may do what he will, and all his doings are just and righteous:
in all his dealings with thee, he, thy dear, tender, nursing Father,
intends good unto thee.

Oh, my soul, when the fountain openeth,
and filleth thee with plenty of all things needful for thee, even then,
dread and fear thou before the Lord; take heed of being exalted in spirit,
and beware of a wrong liberty and false security,
which may soon steal upon thee at such a time, if thou do not abide upon the watch,
and drink the draughts of joy in the pure fear and trembling.
+++[+++Therefore]
oh, my soul, whatever thou enjoyest or receivest from the Lord,
or doest and sufferest for him, keep low in heart, meek in mind, and contrite in spirit,
and then thou art in a safe condition.
When thou appearest wise, strong, rich, and full enough,
even then thou art in greater danger than when thou appearest weak, poor,
and empty in thy own eyes.
Although thou art not then without danger,
but hast cause to fear and watch in all conditions.
Oh, my soul, when thou appearest weak and poor in thy own eyes,
even then take heed of distrust and doubting, but hold fast thy trust in the Lord;
let thy confidence in his name be firm; honour him by believing in him,
and if he slay thee yet trust thou in him, and never leave him; for,
alas! whither shouldst thou go?
he hath the words of eternal life, and is worthy to be glorified, magnified, honoured,
and praised, feared, served, loved, and obeyed forever and forevermore.

Oh, my soul, be watchful, that thou dost not in the least degree seek glory, honour,
and praise to thyself, and to be had in esteem by others;
but wait to feel self wholly baptized into death, and made of no reputation;
take heed that thy left hand know not what thy right hand doeth;
do nothing to be seen of men, or whereby to be accounted of by others,
but in all thou dost, appeal unto Him, who seeth in secret,
and He will reward thee openly.
Seek thou to be known and manifested only to the pure,
unerring witness in all consciences, and to stand justified and approved by it,
and that is enough; no honour, glory, nor praise, but to God alone.
Oh, strive not for lordship over others, but rather strive to be meek, humble,
contrite in spirit, condescending even to the lowest, and serving the meanest in love;
seeking peace and unity among the brethren, with all self-denial;
bearing with the infirmities of the weak, watching for the good in all,
without respect of persons.
Seek thou the glory of God alone, the honour of his name,
the exaltation and spreading of his truth.
Seek the good of all, yea, of thy greatest enemies and persecutors;
desiring the salvation of all people, but not the destruction of any.
And, oh, my soul! be circumspect and vigilant to walk as becometh the gospel,
that I may be an adorning to the truth of God,
a holy example unto all people wherever I come;
that the blessing of the Lord my God may be poured down upon me yet more and more,
+++[+++enabling me]
to become fruitful unto him,
and an instrument in his hand amongst the sons and daughters of men, to the praise,
glory, and honour +++[+++of his name.]

Oh, my soul, watch and fear before the Lord; keep thy eye unto him,
and look not out at others to walk by imitation;
but if thou seest any (whatever they be accounted) do those
things which the Lord doth not allow thee to do,
+++[+++let not their example induce thee to do them,]
but keep close unto the Lord, and take counsel of him.
Do not judge or justify those things which thou hast not a true discerning in,
because another judges or justifies them, but rather be passive in such matters;
stand still and wait upon the Lord for a perfect understanding in all things.

Oh, my soul, seek not liberty to the flesh; beware of that counted freedom,
which is indeed bondage, and which hath stolen upon many in their latter days.
Endeavour to put off those things, which in their place are said to be lawful,
but which +++[+++would if indulged in]
hinder thy growth in the eternal +++[+++Truth.]
And, oh, walk wisely before all men, giving no offence to Jew nor Gentile,
nor to the church of God; knowing there is that which is lawful, but not expedient;
there is that which is lawful, but it edifies not.
Wherefore forbear what may be forborne,
and yet be not brought under the power of any thing below the life;
but seek after those things which make for edification, love, peace, and unity;
for God is the author of peace, and not of confusion, strife, and debate.
Oh, my soul,
thou dost greatly desire that I might not appear
in the sight of any of the Lord`'s little ones,
to be more than what I really am; by the grace of God I am what I am; and his grace,
which he hath freely bestowed upon me, hath not been in vain,
praises to his name forever.
All flesh is as grass; and what is man?
he is but a vessel, wherein God may appear or disappear as he pleaseth;
and indeed the Lord is jealous of his glory, and will not give it to another: wherefore,
my soul, seek the glory, honour, and praise of God alone,
unto whom only it is due forever and evermore.

If there be some who were once fresh, green, living, and fruitful unto God,
upon whom is now come coldness, deadness, and barrenness,
and whose love and zeal for the Lord is waxed cold; how canst thou, oh, my soul,
but fear before the Lord, lest the same should happen unto thee?

+++[+++Therefore]
cleave unto him, look up unto the Holy One, who dwelleth in the high and holy place,
and with thee also, O my soul! as thou art kept humble in heart and contrite in spirit,
trembling at his word.
Look not at thy own weakness and inability, but keep thy eye unto the Lord,
trust in his name, rely upon his arm, and hope in his mercy.
He maketh the poor rich, the weak strong, the simple wise.
Wait thou patiently upon him; look not out at the greatness of others`' measures,
neither look at the smallness of thy own,
lest weariness and discouragement should thereby come upon thee;
but be thou contented with thy portion; be faithful unto the Lord;
and being faithful in the little, thou shalt be made ruler over much,
and enter into the joy of thy Lord.
Wait upon Him, who hath freely given thee what thou hast of him,
and he can give thee more.

Oh, my soul, surely thou hadst never as of thyself, turned unto the Lord,
had he not of his own free will turned thee, and "`after thou wast turned,
thou repentedst, and after thou wast instructed, thou smotest upon thy thigh; yea,
thou wast confounded, because thou didst bear the reproach of thy youth.`"
And after the Lord had turned thee in measure to himself,
surely thou hadst not followed him in the strait and narrow way,
through the cross in the self-denial,
had he not drawn thee after him by the cords and wooings of his tender love;
surely thou hadst turned back again from the Lord,
had he not preserved and supported thee by his own Almighty power.
His grace hath been sufficient for thee, both in prosperity and adversity,
in the time of trial, and in the hour of temptation.
So let all flesh be silent in thee, oh, my soul, the boaster forever excluded,
and the Lord alone honoured and praised, his unspeakable love and free grace admired,
and his holy name feared and obeyed.
What was I, and what was my father`'s house?
I was neither a prophet, nor a prophet`'s son.
What was I, that the King of Glory should cast his eye upon me,
even when I lay as among the pits, that He should hold forth the sceptre unto me,
and that I should find favour in his sight?
Oh, my soul; the Lord hath done much for thee; he hath made crooked things straight,
and laid mountains low before thee; he hath made a way for thee in the wilderness,
and a path through many a thicket; "`He hath lopped the bough with terror,
and the high one of stature hath been hewn down;
he did cut down the thickets of the forest with iron,
and Lebanon did fall by a mighty one.`"

Oh, how hath his love made thee willing to bow thy neck to the yoke,
to take up the cross, to despise the shame,
and to follow the Lamb through trials and tribulations!
Oh, how hath his love caused me to cast off other lovers!
He is become my treasure, and my heart is with Him; so that when I am shut up in prison,
if I enjoy him, oh, then days, months, and years may pass over my head,
and time is not thought long, nor sufferings hard, because of the enjoyment of the Lord,
my treasure; his sweet, refreshing presence, makes a prison delightful to me; praises,
pure living praises to my God forever.
He hath been with me in six troubles, and in the seventh he hath not left me;
he is my buckler, my strength, my rock, my strong tower,
wherefore I will not fear the threats of the wicked,
neither regard the cruelty of the ungodly;
through the strength of my God I will not fear,
though the earth be removed and carried into the midst of the sea;
and though the mountains shake with the swelling thereof; though the heathen rage,
the people imagine vain things, and the rulers take counsel against me.
I will not fear what man can do unto me, for the Lord is with me,
and I shall not be moved; He will help me, and that right early.

I am but a child, weak and feeble, yet having had great experience of the love of my God,
and of his tender fatherly care over me,
how can I but confidently hope in and depend upon him, and believe that He,
the mighty one,
will enable me to wade through and endure the trials he is pleased to exercise me withal?
He hath +++[+++hitherto,]
through his love and mercy, caused my trials to work for my good:
he hath nine times delivered me out of the hands of unreasonable men,
out of their prisons and holes, where through his enabling me,
I have suffered for his testimony without murmuring against him;
praises unto him forever.
I am willing to wait thy season, oh, my God! for thou art with me.
Let me never depart from thee, and then I know thou wilt not leave me; but will help,
comfort, and quicken me still; thou wilt feed me with bread from heaven, fresh manna,
morning by morning, and give me to drink of the river of thy pleasure daily;
thou wilt enable me to stand faithful to thee unto the end of my days,
to finish my testimony for thee, thy name and truth, in this thy day, with joy,
lay down my head in peace, and repose in thy tender bosom of endless love,
with thy dear children forevermore.
Oh! let it be so, thou Holy One! to thy praise, who art worthy of all glory, honour,
and everlasting thanksgiving, forever and evermore.
Amen.
Hallelujah.

Oh, my soul, thou dearly lovest the whole flock of God,
wherever scattered upon the face of the earth; thou greatly desirest their prosperity,
+++[+++even]
that the Lord may bless them with all spiritual blessings in Christ Jesus.
Oh, the Lord God Almighty keep his sheep and lambs,
whom he hath gathered out of the waste, howling wilderness, from the barren mountains,
+++[+++and led them]
into the low, green valley,
where the pure refreshing springs of life eternal encompass them about;
the Lord keep them still and quiet, minding their feeding,
and not at all heeding the raging of the sea, nor regarding the unmerciful waves thereof;
which often +++[+++appear]
very high, and as if they would overflow the valley,
and drown all who flee not to the mountains for safety: but let not the sheep and lambs,
the little ones fear, nor flee to the hills for refuge; for behold,
the Holy One of Israel is their Shepherd, and He continually watcheth over them,
and greatly careth for them.
He it is who hath given bounds to the sea.
He can let forth the wind and suffer a storm, and he can make a calm when he pleaseth.
Let not Israel fear, for the Lord his God is between him and his enemies,
and fights for him against his adversaries; He will look down upon them in his anger,
and trouble their host; He will take off their chariot wheels,
and will blow in his wrath upon them;
He will get himself a name through the destruction of Zion`'s enemies,
and honour and magnify himself through the deliverance of his chosen, +++[+++yea]
all nations shall quake before the mighty God of Israel, who is "`glorious in holiness,
fearful in praises, doing wonders.`"

Oh, let Israel honour his God by believing in him,
and depending upon his arm of everlasting strength; and patiently wait upon Him;
for he that is to come will come, and will not tarry; his work is before him,
and his reward is with him, even joy for the mourners in Zion, beauty for ashes,
and freedom from bondage, burdens, and grievous oppressions.
The Lord will thunder from heaven upon thy enemies, O Zion,
and will break thy adversaries to pieces; He will give strength to thy king,
and exalt the horn of his anointed.
"`He shall reign and prosper, and execute judgment and justice in the earth;
in his days Judah shall be saved,
and Israel shall dwell safely,`" then "`shall it be said to Jerusalem, fear thou not,
and to Zion, let not thine hands be slack; the Lord thy God in the midst of thee,
is mighty; he will save, he will rejoice over thee with joy, +++[+++he will rest in his love,]
he will joy over thee with singing.`"
Thy maker, thy husband,
(the God of Hosts is his name,) will extend joy and peace as a mighty stream,
and endless consolations as a river.
For "`as one whom his mother comforteth,`" so will the Lord comfort Jerusalem;
in the sense whereof her children shall rejoice,
and their spirits shall praise and sing glory unto Him,
who is Lord and King of heaven and earth, who is worthy of all glory, praise, and honour,
forever and forevermore.
Amen.

O Lord God Almighty, keep all thy people retired in thy name;
so that whatever thou sufferest to befall their bodies,
their souls may be safely bound up in the bundle of life.
Oh! increase the patience of thy people, and strengthen the faith of thy chosen;
support the weak, and uphold the little ones, who cannot go alone,
that none of thy flock may grow weary; that all thine may stand in the day of trial,
and be kept in the hour of temptation; +++[+++that they may be]
borne up under all sufferings,
and in the end come forth as gold seven times refined in the fire,
to shine as stars in the firmament of thy power; to declare of thy mighty acts,
and sing of thy mercies and wonderful doings; to glorify, magnify, honour,
and praise thee, thou Mighty One, who art from all eternity,
whose throne is established of old, whose sceptre beareth sway in righteousness,
and whose kingdom is everlasting.
Glory and Hallelujah to thee in the highest, forever and forevermore.
