== Chapter IX. A General Salutation of Love to Friends

Dearly beloved Friends everywhere,
who are faithful to the Lord and his truth in your several measures and places,
who are honest and upright in heart, who love and delight in truth and righteousness,
and seek the praise, honour, and glory of God alone,
my very dear and unfeigned love in the precious truth extends unto you: grace, mercy,
and peace attend you, joy and comfort fill you,
and the blessing of the Most High rest upon and remain in and with you day and night.
The Lord keep you in the faith of the elect seed, in which is your victory over the world.
In +++[+++this]
stand fast, and keep your dominion in the Lord over the earth and earthly things,
that you may sit together in heavenly places in Christ Jesus,
and use the world as if you used it not,
being loose in heart to that which perisheth with the using.

Oh, that all friends who are free from the cares and cumbrances
of this world may prize and stand fast in their freedom,
and not be forward and hasty in the affectionate part,
to run themselves into bondage to those things which profit not,
but which hinder Godward,
and prove as briers and thorns to the choking the
growth of the seed of life in the heart.
There is a mind which desires, and is ready, if it be not limited,
to create unto itself a freedom that stands not in the liberty of the sons of God.
The liberty of the sons of God and children of the light,
stands in that which is a yoke to the world`'s liberty,
and their freedom in that which is bondage to the carnal mind, and +++[+++which]
crucifies unto the world and worldly things.
Also there is a mind that seeks to put off, and to keep out of those things,
which in their proper place may be said to be lawful,
but which hinder a growth in the eternal Truth, and endanger the soul-standing Godward:
truly that is the pure mind which serves one master, God alone.
I desire, dear friends, that this mind may +++[+++be in us]
more and more; that we may be as strangers and pilgrims in and to the world,
and the love thereof, that the Lord alone may become the object of our love,
and that the desire of our souls may be to his name, and to the remembrance of Him.

Oh! dearly beloved friends, much hath the Lord God of power done for us,
since the day that he raised us up from the dunghill of our own corruption,
and said unto us, who were dead in sins and trespasses, live.
Oh, how greatly hath he blessed and prospered us,
and hath even made us a family like a flock,
in despite of the spirit that hath so eagerly sought to devour us,
and to extinguish us from being a people; and though Balak and Balaam`'s spirit,
the beast, Jezebel, and false prophets, have sought enchantments against us, to curse us,
yet the God of blessings has greatly blessed us in our sufferings, tribulations,
and afflictions, and has made Joseph like a fruitful bough,
whose branches run over the wall:
though the archers of Babylon have shot at him and grievously wounded him,
yet his bow (notwithstanding his great affliction) has abode in strength,
and the hands of his arms have been made strong by the hand of the mighty God of Jacob,
who hath blessed Joseph,
and unto the utmost bounds of the everlasting hills shall he be blessed forevermore.

Oh, dear friends! if any people now in being upon the
earth have cause to speak well of the Lord,
and to trust in his holy name, we are the people; for mightily hath he wrought for us,
though the world sees it not.
Oh! how have we been as lambs among lions, and yet not devoured,
but wonderfully preserved by the secret power and invisible arm of the Lord our Shepherd!
When the beasts of the forest have come forth to devour,
and the wolves have been greedy of their prey, then hath the Lord fought for Mount Zion,
and defended the hill thereof; and though some said, "`We will pursue,
we will overtake them, our lust shall be satisfied on them; we will draw our swords,
and our hands shall destroy them;`" yet how hath the Lord blown in his wrath upon them,
the sea of his judgment hath covered them,
they are sunk as lead in the bottom of the mighty waters, and we, through mercy,
are yet alive, to speak well of the Lord, to declare of his kindness,
and to praise him for his works.
Oh! his love, his mercy, and tender fatherly care over us,
extends beyond the demonstration of words;
let the sense thereof be engraven upon the table of our hearts,
that it may humble us and keep us low before him,
and be an obligation upon every soul of us,
to bind and engage us unto him and his truth forever.

How mightily hath the Lord limited and quieted the raging sea, and made a calm!
Oh! that all friends might take notice of his great mercy and love to us in this particular,
and mind his end therein; and let us all take heed +++[+++that]
we sin not, because grace and mercy abounds.
May none get into a false ease and liberty, and wrong security,
because of the present calm, but +++[+++let]
all keep retired in the secret power of the Lord,
which fitteth and maketh ready for trials when they come; in, by,
and through which we have been upheld and preserved hitherto.
The Lord`'s arm is not shortened that it cannot save, but is the same that ever it was;
it hath been our helper in six troubles,
and in the seventh hath not been wanting to us to support
and uphold us when there hath been none to uphold,
and to comfort us when nothing but sorrow and trouble compassed us about.
When we had nothing, as from men, but the bread of adversity and the water of affliction,
when we have been bowed down with the oppression of our enemies,
even then hath the Lord our God been the comforter of our hearts,
the refresher of our soul, the rejoicer of our spirits, and the lifter up of our +++[+++heads.]
His presence hath been with us in the prison-house, and in the low dungeon.
He hath not left us to this day, and assuredly never will leave us, if we leave not him;
but will be with us until we have fulfilled the days of our appointed time,
and our change come.

So, dear friends, unto the Lord I commit you,
who knoweth how it is with all his children, and beholdeth all their trials, straits,
and sufferings, inward and outward; for his ear is open to the cry of the poor,
and the groanings of the needy;
He is all-sufficient for all those that trust in and depend upon Him,
and is able to keep them by his power, through faith in his name,
unto his heavenly kingdom.
So the Lord Almighty be with you all, protect and defend you, keep you from evil,
unspotted from the world, and preserve you in love, peace, and unity with Himself,
and one with another in his innocent, unfeigned love, in his light, life, power,
and truth; and make and keep you all of one heart and one mind;
that with one consent you may still worship and serve
Him in the one spirit and the one truth;
in which I dearly salute you all,
and remain your friend and companion in the patience and tribulation of Jesus,

[.signed-section-signature]
William Bennit

[.the-end]
The End
