[short="Memoir of William Bennit"]
== Chapter I. Memoir of William Bennit

+++[+++William Bennit was a minister of the Gospel among the people called Quakers,
soon after the rise of that people,
and was one who partook largely of the persecution and sufferings to which they were,
for many years after their first appearance, exposed.
It appears, that during the latter part of his life he resided,
when not deprived of his liberty, at Woodbridge, in Suffolk.
In an account of his religious experience, written by himself, he says:]

[.small-break]
'''

When I was but young in years the Lord God of light, life, and power was pleased,
in some measure, to visit me by his pure light in my conscience,
which many a time checked and reproved me for my sins,
and sometimes brought trouble upon my mind on account of them.
But I was not then sensible that it was the light of Christ
Jesus which reproved and judged me for evil,
and at times broke my false rest.
When I was among idle children, such as were void of the fear of God,
I ran into sin and wickedness with them, and took great delight therein;
but when I came to be still and alone in the fields, or elsewhere,
the pure witness of God would arise in me with its reproofs,
set my sins in order before me, and bring my evil doings to my remembrance.
Then trouble took hold on me for a time, and sin became my burden;
but I soon got from under it into ease and liberty,
and went on year after year in rebellion against this witness of God in my conscience,
taking delight in things which I knew were evil.
Yet the Lord, in mercy, hovered over me for good,
and sometimes stopped me from speaking or acting the evil that I intended to speak or do,
and preserved me out of many gross evils.

In those days, when I was alone in the fields, I cried and prayed unto the Lord,
and desires were stirring in me after the knowledge of Him, his way and truth;
but I prayed to a God I knew not: I imagined a God afar off,
and did not then know it was the Lord who searched my heart,
discovered unto me my thoughts, and judged me for sin.
I knew not that it was the light and truth of God in my own heart,
which sometimes begat desires in me to know the truth, and to walk therein;
but my mind was abroad in carnal ordinances, forms, ceremonies, and traditions of men,
and I knew not that it was Truth in me,
which sometimes stopped me from lying and swearing; and when I knowingly told a lie,
accused me for it, when no man could accuse me.
I may truly say, there was something stirring in me, at times, after the Lord,
ever since I was six or seven years of age;
and when I came to be about fourteen years old, and an apprentice,
it pleased the God of infinite lovingkindness, to visit me more closely than before; yes,
he did, by his pure light and gift, pursue me hard,
calling to me in my heart to come out of sin, out of evil words and works.
Still, (like Samuel, when he was a child,) I knew not that it was the Lord who called;
for he was, though near me, as a stranger to me; I knew not his voice,
but went astray as a wandering sheep; yet had I desires to know the way to the fold,
to know where the Lord feeds his flock, and causes them to lie down in peace, quietness,
and rest, where none can make afraid; for indeed it was rest I wanted,
and true peace in God my soul many a time panted after.

Oh, I was oftentimes wounded because of sin;
and for lack of the enjoyment of the love and peace of God,
I went bowed down in spirit day after day,
with my eyes filled with tears and my heart with sighing, and I thought there were few,
if any, in my condition.
Sometimes I would say, in my heart, "`Oh, that I were in a desert,
solitary place outwardly,
(for such was my condition inwardly,) where I might
mourn and pour out my tears to the God of mercy,
and spread my complaints before him whom my soul thirsts and pants after,
even as the hart pants after the water-brooks.`"
Many a time did I get into a solitary place, to ease my heart a little,
by pouring out my tears and complaints to the Lord.
In those days many were my prayers, and great the burden under which I went,
not then knowing the light of Christ in my conscience
to be a stay to my mind and a bridle to my tongue.
Many a time I got into a false ease and liberty, into idleness and youthful wildness;
but sorrow and trouble would again take hold of my mind,
and again would true desires be renewed in me after the Lord.
My heart was often made tender and soft,
compassion was in me towards any who I thought were in my condition:
a tender love was hidden in my heart towards those
that I then thought were the people of God;
and I can truly say my heart is open still, and oftentimes pity, love,
and tenderness issue from me towards those who are in that condition.
Oh, my soul cannot but sympathize with them,
and that not without some secret cries unto God on their behalf.
It is partly for their sakes that this is published,
with the hope that it may be of service to some of them;
and if the Lord order it so to be to them, or to any, my end herein will be answered.

In those days I frequented the meetings of the people called Independents,
in Great Yarmouth, whom I then thought to be the people of God;
but I saw that many of them, and even some of the chief of them, were not,
in life and conduct, what they professed to be: and when I have been among them,
in the time of their singing Psalms, the pure witness of God in my own heart, has,
as it were, stopped my mouth, that I could not sing with them;
but my heart has been broken into tenderness, and many have been my tears;
my outward man has trembled and been shaken like a leaf that is shaken with the wind.
This was before I was called a Quaker, or had seen any of that people.
The working of the power of God in my heart did, in some measure,
let me see that it was not then a time of singing for me; for I was in a strange land,
in the land of captivity, and could not sing the song of Zion;
and this song I may truly say, without the least enmity against that people,
(for my soul bears love and good will towards all men,) they were ignorant of,
while singing what others had prescribed and made ready for them.
I then lacked the enjoyment of the love, joy, peace, and secret presence of God,
which makes glad the hearts of the righteous,
and causes the lowly and upright to sing the new song, which the living only can sing,
even the ransomed of the Lord, who are returned from Babylon to Mount Zion.

In all the time of my trouble of mind and travail of spirit,
I never made known my condition to any creature, but kept it secret in my heart,
pouring out my complaints to God only.
I would gladly have had some to know how it was with me; but I was straitened in myself,
and therefore kept my state of mind in obscurity.
I still knew not what it was that wrought and strove with me,
which did so frequently judge and reprove me for sin,
gave me power over many evils which others were overcome with,
and raised strong desires in me after the Lord.
I say,
I was not then sensible that it was the light of Christ Jesus which thus strove with me;
nor that I should have taken heed thereunto, as unto a light shining in a dark place,
until the day had more and more dawned, and Christ, the day-star, had arisen in my heart,
over all my enemies; but I was still hunting abroad, for that which was within me;
the pearl of great price was hidden in my heart;
but I knew it not--the kingdom of God was at hand, and was working in my heart,
like leaven hid in three measures of meal; but I was gazing for it abroad:
my Saviour was near, but I imagined him afar off.

In those days no man directed my mind to the light of Christ in my own heart;
for the teachers of the people would say,
that which troubles a man for his sins is a temptation of Satan,
and thus instead of directing the mind to the light, they drew away from it.
Is it the devil`'s work to discover, judge, and condemn for sin?
Is it not his work to lull people asleep in sin,
to cry peace to them in their iniquities,
and to keep them satisfied with a profession of God, without the possession of a holy,
undefiled life?
Is it his work to destroy his own kingdom, which is sin?
Surely no; that is the work of Christ, the light of the world.
I do now infallibly know, that it was the pure witness of God, the light of his Son,
Christ Jesus, a measure of his free grace and truth in my heart,
which in those days brought trouble upon me for my sins,
and begat good desires in me after the Lord.

But, alas, for me! after all this long visitation of the love, goodness,
and mercy of the Lord to my soul, and after all this trouble of mind, travail of spirit,
desiring and seeking after the Lord, I got into a false ease and wrong liberty,
became careless, and by disobedience quenched the strivings of the light of Christ in me,
insomuch that I felt little of the burden and sorrow
which before lay so heavily upon my mind;
my face was turned back again into Egypt,
which before had been partly turned towards Canaan, the land of light, life, and rest;
and I ran into evils which I had formerly, by a secret power, been kept out of.
I grew loose, careless, and wicked; my mind was taken off from seeking the Lord,
and went after the vanity, pleasures, and idleness of the world;
delighting much in music and dancing, sporting and gaming,
and so made merry over the pure witness of God, by rebelling against it,
and rejecting its reproofs and strivings.
Oh, the patience and long-suffering of the Lord was large towards me in that day!
He who, in his justice, might have cut me off in my sins and rebellion,
and thus made me an example of his wrath, waited to be gracious to my soul,
day by day and year after year.
His mercy and long-suffering was exceedingly large to me, and is not to be forgotten;
but in and by the Spirit of Truth am I to be kept in a living remembrance thereof.
He would not that I should perish from his presence forever,
and in the sense thereof he is worthy to be praised and honoured by my soul.
For after all this, the Lord God, of tender compassion,
was pleased to visit my poor soul again--he remembered the poor and needy,
the captive exile, to deliver him out of the hand of him that was too strong for him,
and to loose him, that he might not die in the pit, and perish in the miry clay.

I now heard the everlasting gospel of light, life, and peace preached by his servants,
in scorn called Quakers,
and the pure witness of God in my heart bore testimony to the truth declared by them.
But long it was, after I was in some measure convinced of the truth,
before I freely gave up my heart to obey it; yet the Lord, in time,
overcame my heart by the power of his love, his unspeakable love,
and made me willing to resign my heart in obedience to him and his truth,
to bow to the yoke, to take up the daily cross, despise the shame,
and follow him in the way of truth and righteousness.
Herein I have found peace, rest, and true satisfaction to my soul;
and although it has been my portion, with many other brethren,
sometimes to eat the bread of adversity, and to drink the water of affliction,
yet my Teacher and Comforter, whom I witness to be near, can none remove from me.
He has been and is with me in the prison-house, and in the low dungeon.
That which formerly reproved and judged me for evil,
and raised desires in me after the Lord, now keeps me in peace with him,
and in fellowship with his people;
though I deny not that I have now a greater measure of light and grace than I then had;
for although the light or seed of the kingdom be in the unbeliever and unconverted,
even as the least of all seeds, yet in whomsoever it is received in faith, love,
and obedience, it grows till it is the greatest among herbs, and becomes a tree;
under its shadow they sit with great delight, and its fruit becomes sweet to their taste;
as a little leaven hid in three measures of meal,
it operates in the hearts of those who believe in it,
until it has wrought out the old leaven of malice, sin, and corruption,
and leavened the soul into its own nature.

The same light which condemned me for sin, when I was in disobedience to it,
now saves me from sin, justifies me as I am kept in the faith and obedience of it,
and ministers to me rest and peace.
So this I assert and affirm experimentally, (against all opposers, gainsayers,
and undervaluers of the light) that the light of Christ
in the conscience of that man or woman who is in unbelief,
and in the unconverted state,
is one in nature with the light in that man or woman who is in the belief of it,
and converted by it:
and the light of Christ in the conscience of the drunkard and swearer, that does check,
judge, and reprove him for his sins, if it be believed in, loved, and obeyed,
is able to save him from his sins.
They who love evil, hate the light, and reject it, do not witness the saving,
healing virtue, the restoring, redeeming power of the light;
it is to them a judge and condemner;
but they who receive it in the love and belief thereof,
receive power to become the sons of God, and joint heirs with Christ,
of the kingdom of God, which endures forever.

So blessed be the Lord my God, who is worthy to be praised in the sense of his love,
goodness, and grace; and having obtained mercy of Him,
and experienced his tender fatherly dealings towards me,
my heart is opened with love and good will to all people,
desiring their good and eternal welfare in God.
