== Chapter II. Testimonies Concerning William Bennit

+++[+++That which now follows is taken from two testimonies concerning William Bennit,
written respectively by Edmund Cross and William Pearce,
two Friends who suffered imprisonment with him, and who,
from their intimate acquaintance with him,
appear to have been well qualified to describe his character.]

[.small-break]
'''

William Bennit was a man wholly given up to serve the Lord,
and what he did for Him he did with all his heart.
Great was his care over the church of Christ; and when in bonds for the Gospel`'s sake,
he gave forth various epistles full of heavenly exhortations and comfort.
He had the true qualifications of an elder and minister of Christ, walking in holiness,
meekness, and godly fear; never exalting himself above any,
but showing himself an example of humility and self-denial.
Although he was of a weakly constitution of body,
yet when engaged in preaching the Gospel, he was so upheld by the mighty power of God,
and carried forth with such fervency and zeal, that there appeared no infirmness in him;
and notwithstanding his bodily weakness he often travelled in the service of the Gospel.
He had a very good gift in the ministry, and was well acquainted with the Holy Scriptures.
That ardent love by which he was drawn forth to serve the Lord,
flowed from him in the assemblies of God`'s people,
as sweet streams from a pleasant fountain, to the nourishment of the true birth;
in the sense whereof his heart was often filled with
great strength of life and heavenly courage.
He was often concerned to exhort Friends to remember their first love,
and the day wherein they received the truth; and although they had experienced much,
and witnessed a large increase in the riches of God`'s kingdom,
still to stay their minds on the measure of his gift or grace in themselves;
reminding them that Jacob was commanded by the Lord,
after his many trials and great increase of riches, to go to Bethel,
the place where the Lord first appeared to him, there to dwell and erect an altar.

He also often put Friends in mind of speaking the pure language,
by saying "`thee`" and "`thou`" to a single person, without respect of persons;
and exhorted them to feel the concern of truth upon their spirits,
and in the drawing of the love of God, to assemble in his name and fear.
He wrestled much in prayer with the Lord, for the good of all,
particularly for such as suffered imprisonment for the testimony of a good conscience.
He often prayed that God would be pleased to make the prison as a palace to them,
through the incomes of his heavenly life and blessed presence to their souls;
that he would comfort such as lay upon a bed of sickness,
and support such as travel by sea or land in his work and service;
and accompany them with his living power and presence,
in order that their service might be effectual.
He prayed also for his enemies,
that it would please the Lord to turn their hearts and open
their eyes to see against whom they were striving,
that they might behold Him whom, with their sins, they had pierced--repent, be converted,
and healed.
Thus did the love of God flow from this his servant, not only to friends but to enemies,
having so learned of his master, Christ Jesus,
whom he faithfully served in his generation.

The Lord employed him in his vineyard, both to plant and water;
and it was his delight to break up untilled ground,
often having meetings where no Friends had been before.
His Gospel-labours were very much blessed,
and through his plain and prevalent ministry many were added to the church.

He proved himself very faithful, not only in word and doctrine,
but also in life and conduct.
Even his enemies were made to confess that he was a man of an honest, godly,
and upright life: not only in the town of Woodbridge, where he dwelt,
but wherever he was known, his life preached truth, his carriage was innocent,
and his words were very savoury, ministering grace to his hearers.
He was indeed one to whom the Lord had, in a large measure, fulfilled his promise,
to "`make a man more pure than fine gold, yes,
than the golden wedge of Ophir;`" for having been tried in the furnace of affliction,
he became a vessel of honour, fitted for the Lord`'s service; as, says Solomon,
"`Take away the dross from the silver,
and there shall come forth a vessel for the finer.`"

He was, for his testimony to the truth, cast into various jails.
The places of his longest imprisonment,
and in some of which he was confined at several different times, were Yarmouth, Norwich,
Bliborough, Melton, Ipswich, and Edmondsbury.
In the last-named place he lay among felons nearly eight years,
and was kept so close a prisoner,
that during five years of the time he scarcely set his foot over the threshold.
On the 12th of the sixth month, 1683, he was, while upon his knees in prayer,
at a meeting at Woodbridge, violently haled away by a constable,
and with several other Friends taken before a justice, who committed them to Melton jail,
for being, as the court order declared, at a "`Quakers`' meeting,
which is contrary to law.`"
He was kept a close prisoner at Melton till the next sessions,
which were held at Woodbridge, where an indictment was preferred against him,
for being "`riotously and routously assembled with many others,`" etc.
To this charge, (after advancing many sound arguments,
to prove the meetings of Friends to be without any
other object than to wait upon and worship the Lord,
and therefore in no way hurtful or dangerous to the government,
etc.) he pleaded not guilty.
It was then asked,
whether he would give bail for his appearance at the next quarter-sessions,
and to be of good behaviour.
This he refused to do, knowing he had not misbehaved himself;
he was therefore remanded to prison, and again kept very close till the next sessions,
when he was, with some other Friends, brought into court and put on trial.

Much argument took place between the prisoners and the court; and the jury,
after having retired for a considerable time, declared the prisoners not guilty.
This highly displeased the chairman, who persuaded the jury to alter their verdict,
and find the prisoners guilty of an unlawful assembly;
and as if this was not usage sufficiently hard,
William Bennit although then very weak was sent off,
in the latter part of an intensely cold day,
(the snow falling very fast all the way,) to Ipswich.
It was late in the evening before he reached the prison; and for lack of beds,
and timely notice to make provision, this tender man was obliged, wet and cold as he was,
to sit up all night.
It was truly grievous to witness this cruel treatment;
yet the innocent sufferer was preserved in patience and resignation, saying,
in allusion to this journey, "`If it lay in his freedom to go or not,
although he might gain much as to the outward he could not go, such was his weakness;
yet for the truth`'s sake he was freely given up,
though it might prove the dissolution of his body,`" as indeed it so happened,
for he never got over it, but continued to grow weaker,
till upon the 23rd of the 4th month, 1684, in the prison-house at Ipswich,
the place of his confinement, he finished his testimony,
and laid down his head in perfect peace.
At the hour of his departure, while his dear wife, with several other friends,
were sitting by the corpse in retiredness of mind, very sorrowful for their great loss,
the love of God broke in upon them in an abundant manner,
to their great refreshment and satisfaction.

May we who survive, be found working the work of God in our day,
by answering his requirings, that so we like this faithful servant of Christ,
may finish our course with joy, and lay down our heads in peace!
