[short="A Salutation of Love to Professors"]
== Chapter IV. A Tender Salutation of Love and Good Will to Professors

The Lord God Almighty is looking down upon the sons and daughters of men,
and beholds many of them as poor scattered sheep, without a shepherd;
wandering as in the waste, howling wilderness; hungry and thirsty,
seeking diligently for food upon the barren mountains,
running from one broken cistern to another,
yet unable to find that which would truly satisfy and refresh their souls; seeking rest,
but finding no true rest;
desiring to know where the good Shepherd of Israel feeds his sheep and lambs,
and where they lie down in quietness, free from the fear of evil.

The Lord has seen this, and is moved with pity and compassion towards such as these;
and for his own seed`'s sake he is in mercy stretching
forth the hand of his lovingkindness to them,
to gather in one the scattered and dispersed, to bring home the wanderers, the prodigals,
(who have long fed upon the husks among the swine,) to the Father`'s house,
where there is bread enough, and where water fails not.

Yes, the Lord of heaven and earth has lifted up an ensign for the nations,
and will assemble the outcasts of Jacob,
and the dispersed of Judah from the four corners of the earth.
He will return the captivity of his people, and then shall Jacob rejoice,
and Israel be glad.
The stem of Jesse shall stand for an ensign to the people;
unto Him shall the Gentiles seek, and his rest shall be glorious.
He has righteousness for the girdle of his loins,
and faithfulness for the girdle of his reins;
He has put on the garment of vengeance for clothing,
and is clad with zeal as with a cloak; He has on a vesture dipped in blood,
and his name is the Word of God.

This is he whom the Lord gives for a covenant of the people, for a light to the Gentiles,
to be his salvation to the ends of the earth: this is he who makes all things new,
who causes old things to pass away, and creates a new heaven and a new earth,
wherein dwells righteousness; this is he who is the strong arm of God`'s mighty power,
stretched forth to deliver the poor and needy out of the hand of
him who is too strong for him--the hand of his lovingkindness,
which in mercy is stretched forth towards those who cannot be satisfied with the husks,
shells, and shadows, but thirst after Him, the substance.

Ah! dear people! this is the salvation of God, the Word of eternal life:
"`in him was life, and the life was the light of men.`"
He is "`the true light, that enlightens every man that comes into the world.`"
He had a body prepared him, in which he suffered the will of him that sent him;
was born of the Virgin Mary, was circumcised the eighth day,
was baptized by John the Baptist, ate the passover with his disciples,
(for he came to fulfill all righteousness,) was betrayed by Judas,
judged to die by Pontius Pilate, crucified outside the gates of Jerusalem,
rose again the third day, (according to the Scriptures,) ascended into heaven,
and sits at the right hand of God,
glorified with the same glory that he had with the Father before the world began.
And his disciples, according to his command,
waited at Jerusalem till they were endued with power from on high,
and had received the promise of the Holy Spirit, the Spirit of truth;
then they witnessed his word fulfilled, "`He dwells with you, and shall be in you.`"

This is the immortal Word which was in the beginning, and which Paul preached, that is,
Christ within, when he said, "`Who shall ascend, that is to bring Christ down from above,
or who shall descend, that is, to bring up Christ again from the dead:
but the word is near you, even in your mouth and in your heart, that is,
the word of faith which we preach.`"
And he exhorted the Corinthians to examine themselves, whether they were in the faith;
to prove themselves; adding "`Do you not know yourselves, that Jesus Christ is in you,
except you be reprobates?`"
And John, in his writing to the saints, reminds them of that within,
which they had heard from the beginning, "`Let that therefore abide in you,
which you have heard from the beginning.`"
"`If it shall remain in you, you also shall continue in the Son and in the Father.`"
"`But the anointing which you have received of him, abides in you,
and you need not that any man teach you;
but as the same anointing teaches you of all things, and is truth, and is no lie.`"
And as Christ, "`the Truth`" in them, did teach them,
they witnessed the power of God within, the Word near in their hearts,
the Spirit of God in their inward parts, by which they were led and guided,
taught and instructed.
"`For,`" says Paul, "`as many as are led by the Spirit of God,
they are the sons of God;`" and, "`if any man have not the Spirit of Christ,
he is none of his.`"
"`That which may be known of God, is manifest in them.`"
"`The manifestation of the Spirit is given to every man, to profit withal.`"
"`The grace of God, that brings salvation, has appeared unto all men, teaching us,
that denying ungodliness and worldly lusts, we should live soberly, righteously,
and godly, in this present world.`"

Thus the saints felt and knew that in themselves, of which they were born again,
even Christ in them, the seed incorruptible, "`the Word of God,
which lives and abides forever.`"
By this they were begotten again unto God; even they who were once as dead stones,
were raised up to be living children unto Abraham;
they came to feed upon the bread of life, and to drink of the cup of blessing;
by one spirit were baptized into one body, and were made to drink into one spirit,
wherein they worshipped and served the Lord,
and by which their souls were united unto each other, and unto Him, who is God over all,
blessed forever.

Ah! dear people! in whose hearts there are true desires,
and secret thirstings after the living God,
wherever you are scattered among the many sects,
towards you does my soul yearn with love and good-will,
desiring that you may come to enjoy that which you are seeking after,
to possess that which you are thirsting for.
You, who have been seeking God where you cannot find him,
and have been running from mountain to hill, and from hill to mountain,
from one broken cistern to another, and from one dead form to another,
but remain unsatisfied,
and are sensible that you still lack the enjoyment of the love and sweet peace of God,
and groan daily under the burden of sin and corruption,
with desires to be set free therefrom; oh! you who have been thus seeking a God afar off,
retire inward, wait to know the Lord God near you, his pure Spirit in you,
to lead and guide, to teach and instruct you.
"`God is a spirit,`" and his teachings are spiritual: He must be known in spirit,
and worshipped in spirit and in truth; not at the mountain, neither at Jerusalem,
not in this set form, nor in the other form, as "`Lo here! and lo there!`"
In the spirit is the Lord God known and worshipped aright;
and so they who are born of the Spirit,
who live in the Spirit and are taught and led by the Spirit of truth,
are acceptable worshippers with the Lord.
It is the purified sons of Levi, who have passed through the fire,
that are purged even as gold is purged, and tried as silver is tried, by Him,
the Light of Israel, (who is as a refiner`'s fire,
and like fuller`'s soap,) that can offer unto God an offering in righteousness,
and whose offerings are pleasant unto the Lord; but the polluted sacrifices, the halt,
the blind, and the lame, are an abomination unto the God of purity,
who is blessed forevermore!

This is a tender invitation unto you,
who have been spending your money for that which is not bread,
and your labour for that which has not yet satisfied your souls,
but are still thirsty for lack of drink, and hungry for lack of food.
Oh! dear people! hunt no longer abroad, run no longer from one broken cistern to another,
wait no longer at the wells that men have dug, draw no longer at them,
for still you thirst again.
Oh! turn your minds inward, and wait to find and feel that in you,
which you so carefully (and with sorrow) have been seeking without you,
even the water that Christ gives, as he said to the woman of Samaria,
"`Whoever drinks of the water that I shall give him, shall never thirst;
but the water that I shall give him shall be in him a well of water,
springing up into everlasting life.`"
So the water that Christ gives is within, therefore turn inward,
to his pure gift in your own hearts, to his light in your consciences;
for that comes from him, and leads to him, the fountain of living water.

Dear people,
it is not enough to confess and believe that Christ died at Jerusalem for sinners,
and that he has done all for you;
for the drunkard and swearer will make a confession of Christ in words,
as many professors do, who say, they are justified by Christ,
and he has done all for them; and yet they are still in their sins,
in the pride and covetousness, vanity, pomp, and vain glory of the world;
in its vain customs, inventions, and traditions,
seeking and loving its honour and respect, the praise of men more than the praise of God.
It is not enough to confess Christ without, and say you believe in him,
etc. except you come to know him made manifest in you, to destroy the works of the devil;
for your thus professing and confessing Christ, does not cleanse your hearts,
nor sanctify your souls; but still you see you are bond-slaves unto sin and corruption,
and led captive by the lusts and desires of your own hearts.

It will be so, dear people, until you turn your minds inward,
to the pure light of Christ in you, that discovers the sin and corruption of your hearts.
As you come to believe in that, to love and follow that,
you will find it working out the old leaven of sin, iniquity, and corruption,
and working you into its own nature;
and so you will come to see your regeneration wrought by Christ, the immortal Word,
to be born again of the seed incorruptible, which must be known within,
to bruise the serpent`'s head, the god of this world,
the wicked spirit that leads man into sin,
and which has been exalted in the heart of man, has been lord, head, and king there.
The holy seed, the pure life has suffered, has been "`pressed under you,
even as a cart is pressed that is full of sheaves;`" you like sheep have gone astray,
and followed your own way.
But, oh! return unto the "`good Shepherd,`" who laid down his life for his sheep,
and who would gather the scattered into the fold of rest,
and cause them to lie down in the fresh pastures of life,
where none can make them afraid; to feed and sup with him, who is their life, their rest,
their love, and delight.

So, dear people,
because I fervently desire that you might come to
taste of the love and sweet peace of my God,
which is that which would satisfy your souls,
I beseech you to take heed to that in your hearts,
which is as a light that shines in a dark place,
discovering unto you the deeds of darkness and the works of the night to be evil:
and fear not that it will deceive you, for it is the sure word of prophecy,
unto which you will do well to take heed, until the day dawn in your hearts,
and light shine out of darkness, and wholly extinguish the night.
Give no heed to them who speak evil of the way of the Lord, and count truth to be error,
and light darkness.
The professing Jews boasted of Moses, the law and the prophets, but when He,
whom Moses and the prophets prophesied of, whom the law did figure out,
who fulfils the law, who was the life of Moses and the prophets, came unto them,
they hated him, and said, "`We know that God spoke unto Moses; as for this fellow,
we know not where he is from; he is a glutton, a wine-bibber,
a friend to publicans and sinners: he, through Beelzebub, the prince of devils,
does cast out devils,`" etc.

And truly I may say, (not out of a prejudiced mind towards any,
for my soul bears love and goodwill towards all men,) it
is the same now with many of the professors in this age,
as it was with the Jews, who made a large boast and profession of Moses, the law,
and the prophets, and hated Him, who is the life of them;
so these make a large boast of Christ in words, and of his dying in Jerusalem,
(which I believe he did,
according as the Scriptures testify,) and that he has done all for them,
and if they can but believe it, that is enough, etc.
And yet, while they are thus professing him in words,
behold many of them are enemies to his life, and so enemies to him whom they boast of,
who is the Word that was in the beginning, in whom was life,
and the life was the light of men: "`The true light,`" says John,
"`that enlightens every man that comes into the world;`" but the professors say,
it is a natural light, which convinces wicked men of sin in their own hearts,
and judges them for evil doing, and so call the life of the Word,
which is the light of men natural; it is a natural conscience, say some,
it is an insufficient light, it is a common grace, etc.; (so common it is indeed, that,
as Paul says, it has appeared unto all men,
even that grace that brings salvation;) indeed, some will blasphemously presume to say,
it is a spirit of delusion, a spirit of error; and these call the light darkness,
and the good evil; and they one day shall know their blasphemy,
and their words shall become their burden, these are in great darkness and ignorance;
yes, thick darkness fills their habitation, even the darkness of Egypt, that may be felt;
and it is hard for them to be brought into the pure light, and unchangeable truth of God,
although with the Lord God Almighty nothing is impossible.

These are like the Scribes and Pharisees, who, although they professed God in words,
and said they had one Father, even God, sought to shut up the kingdom of Heaven from men,
and would neither go in themselves, nor allow them that were entering to go in.
Whoever you are, and whatever by men you are accounted of,
that does make a large profession of God, Christ, and the Scriptures of truth in words,
and does hate and speak evil of the light, the true "`light,
that enlightens every man that comes into the world,`"
you are a hater of God and of Christ,
and are of Antichrist against Christ, although you profess him in words,
and say you are saved by him, and justified by him, etc.;
yet if you hate his light in your own conscience,
which does check you for evil doing and prick you for your sins in secret,
you are in enmity to him, and condemned by the light, and not justified;
and your confession of Christ in words will not save you from his righteous condemnation,
and your profession is for the fire,
and unto the light you must come before you can find true peace with the Lord God.

Yes, whoever you are who are climbing up in your imaginations,
and soaring aloft with the god of this world, the Prince of the power of the air,
above the light, you must come down;
come down to that which appears a small thing in your eye,
even to that which you count a foolish thing, a weak, a poor thing,
not worth your minding or heeding; but this is it, the foolish thing in your eye,
that is to confound your wisdom, and turn it into foolishness,
that so you becoming a fool, may be made wise in it.
This is the weak thing in your eye, which is to confound your strength,
and make you weak, that you may be strong in it; and the poor thing in your eye,
which is to rob you of all your riches, that you, becoming poor, in it may be made rich.
For where is the wise, the Rabbi, the scribe, the disputer of this world?
Has not God made foolish the wisdom of this world?
for the world by wisdom knows not God; and so the boaster is excluded,
that God may have the glory, and all flesh be abased and silent before Him;
for He is worthy of all glory and praise forever!

So heed not, dear people,
(you who have any desire in you after the Lord,)
what this man or the other says against the light;
but love the light, and take heed unto it; for that which judges and condemns sin in you,
you need not fear will delude you; but beware of that which leads into sin and evil,
that is a spirit of delusion.
"`All things that are reproved are made manifest by the light,
for whatsoever does make manifest is light;`" and
this will not only make manifest the sin and evil,
but as you turn your minds inward unto it, and love and follow it,
it will save you from your sins, and redeem your souls unto God;
for they who receive his light, his pure grace in them,
receive power through it to become the sons of God;
for through his grace does he manifest his power in them that believe in the light,
to the drawing their hearts and minds out of ungodliness and worldly lusts,
and teaching them to live soberly, righteously, and godly in this present world;
and thus the free grace of God brings salvation to their souls.
And so, dear people, as you come to believe in the light,
to love and obey the light in your own consciences,
you will feel and witness the work of the Lord God in your hearts,
the operation of the Word of life, to the casting out of the bondwoman and her son,
who is not to inherit; to the binding of the strong man, and casting him out; yes,
the old man with his deeds is to be put off;
you are to be renewed in the spirit of your minds, and the new man is to be put on, who,
after God, is created in righteousness and true holiness.

So coming to the light, Christ Jesus, you come to the substance,
to him in whom the figures, types, and shadows end; and to witness him in you,
who fulfils all righteousness;
you will be circumcised in him with the circumcision made without hands,
by the putting off the body of the sins of the flesh,
of which the outward circumcision was a figure, and experience the baptism of Christ,
which is with the Holy Spirit and fire,
of which John`'s baptism with outward water was a true figure.
John bare testimony unto Christ, the light of the world, and said, "`I must decrease,
but he must increase.
I indeed baptize you with water, but he (Christ Jesus,
who was before me,) shall baptize you with the Holy Spirit and with fire;
whose fan is in his hand; and he will throughly purge his floor,
and gather the wheat into his garner,
but the chaff he will burn up with unquenchable fire.`"
The day of gathering is come, wherein the Lord God is gathering the dispersed,
seeking that which was lost, bringing back that which was driven away,
healing that which was sick, and binding up that which was broken,
but the strong and the fat he is feeding with judgment.
The Lord is gathering people out of the forms and shadows, wherein many have long stuck,
and is bringing them to the substance and life itself,
out of the many sects and various ways, into the one way of life, light, peace, truth,
and righteousness; and by the one Spirit is baptizing them who believe in the light,
into the one body, wherein the unity, the oneness, and the fellowship is witnessed;
blessed be his name.

The way of the Lord is pure, righteous, and unchangeable; "`I am the way, the truth,
and the life,`" says Christ, the immortal word.
"`No man comes unto the Father but by me.`"
"`I am come a light into the world,
that whosoever believes in me should not abide in darkness.`"
Therefore, dear people, love the light; and "`while you have light, believe in the light,
that you may be children of light,`" and heirs of an inheritance incorruptible,
that will not fade away.
There is no obtaining the crown but through the cross, and this you will know,
who come to love the light, to learn of Him who is meek and lowly in heart,
and to follow him in the strait and narrow way which leads to life.
"`If any man will come after me,`" (says Christ,) "`let him deny himself,
and take up his cross and follow me.`"
If you be followers of the light, you will know a daily denying of self,
a denying of your own wills, your own desires, thoughts, and affections,
your own words and works, your own wisdom and righteousness;
an hourly living in the cross, through which you must come to be crucified to the world,
its vanity, pomp, pastime, and pleasures, its sins and iniquities, vain words, works,
fashions, customs, inventions, and traditions;
so coming to be crucified with Christ unto the world,
and to be baptized into death with him, you will live with him unto God,
in the life of righteousness; and in him then you will find that rest, satisfaction, joy,
comfort, and peace, which no man can give unto you.

So, dear people, who are seeking the Lord,
and desiring to find peace and comfort to your souls,
this I leave with you--flee not from that which judges you in your own hearts,
for sin and evil, which brings sorrow upon you,
and wounds you in secret because of transgression.
How many are there who, when they have been judged by God`'s pure light in their hearts,
have run unto vain helps, even to those who could not speak a word in season to them,
but who have daubed them with untempered mortar,
and endeavoured to heal their wound deceitfully,
by preaching peace to that which is for judgment.

They have thus run from one physician to another,
until at last they have said in their hearts, "`We will seek no more to man,
for vain is the help of man; but we will return unto the Lord God, who has wounded us,
and he will heal us; who has broken us to pieces,
and he will bind us up;`" and so returning to the
light of Christ Jesus in their own hearts,
(by which the Lord had wounded them for sin,) and waiting therein, in patience,
upon the Lord, in the way of his righteous judgments, which were set up in their hearts,
they came to feel, through believing in and loving the light,
the cause of their sorrow and wounds taken away by the blood of Jesus, which is his life,
and which has cleansed them from their sins;
and so the very cause of their wound being taken away, and the corruption purged out,
then He who in mercy towards them had wounded them, healed them with the oil of joy,
peace, and gladness: and now those that were mourners do rejoice;
beauty is given them for ashes, the oil of joy for mourning,
and the garment of praise for the spirit of heaviness,
and they are become trees of righteousness, the Lord`'s own planting,
bringing forth fruit to his glory and praise.

These can say, "`Good it is to wait upon the Lord in the way of his judgments.
Lo, this is our God, we have waited for him: come,
let us rejoice in his salvation with which he has saved us;
he has redeemed us out of the horrible pit; out of the miry clay has he brought us,
and set our feet upon a rock, and does establish our goings.
He fills our souls with the fatness of his house,
and causes us to drink of the river of his pleasure.
Oh! what shall we render unto the Lord our God for his benefits?
Let us take the cup of his salvation, and drink thereof abundantly;
and in the strength of its virtue, in the meekness of our hearts,
and in the lowliness and contritedness of our souls, praise the name of the Lord our God,
who is worthy of all glory and praise forever and forevermore.`"

P+++.+++ S. A few words more unto you, dear people,
who desire the love and peace of God more than the glory and pleasures of the world.
Take heed unto that which discovers unto you what your thoughts are,
whether they be good or evil; for it is that which must redeem your minds unto God;
wait to know it to be a stay to your minds, a stop to your thoughts,
and a bridle to your tongues;
raising a holy fear in your hearts of offending the God of righteousness in thought,
word, and deed.
Dear people, retire inward, to the manifestation of the Spirit of God in your own hearts,
and wait in it to know the Lord God to be your teacher;
so that if you should be separated from those that have been your teachers,
and put into a hole, a dungeon, or cave of the earth for your consciences towards God,
and be separated from all your outward teaching,
you may then feel and witness the Lord to teach and instruct you,
to counsel and direct you, to comfort and refresh you,
even by his pure eternal Spirit in you;
for all the children of the Lord shall be taught of him,
and established in righteousness;
and great shall be their peace in the God of their salvation; unto whom be honour,
praise, and glory in the highest, forever and evermore, for he is worthy, worthy, worthy,
says my soul.
Amen.

William Bennit
