[short="To the Suffering Lambs in Prison"]
== Chapter V. To the Suffering Lambs of the Lord`'s Flock in Prison

Dear, suffering, tribulated lambs of my Maker,

The tender unfeigned salutation of my soul reaches unto you,
in the love of the unchangeable truth, whereof God has made us partakers,
of which he has made us witnesses, and for which he has (through his love,
his constraining, overcoming,
powerful love) made us willing to part with and be
separated from our dearest friends and nearest relations,
and to endure whatever sufferings he shall permit to be inflicted upon us,
rather than for any by-ends and self-interest,
to do that thing willingly which we know would cause his truth to suffer,
his holy name to be dishonoured, his holy Spirit to be grieved,
and our consciences to be defiled.
Ah, in this frame of spirit, and freely given-up state, the Lord keep us by his power,
for his own name`'s sake, even unto the end, until our testimony for him, which he,
in his beloved Son, has counted us worthy to bear, in this his day, be finished,
to the praise, glory, and renown of his holy powerful name,
and to the everlasting joy and peace of our immortal souls.
Amen.

My soul fervently desires that the holy, living presence of my God may be in, with,
and among you all, to your joy and comfort; that his power may uphold you,
and keep up your heads above all your sufferings and trials,
that so none may faint or grow weary, but that you may be made strong in the Lord,
and be able, in the power of his might, to resist and beat down all carnal reasonings,
and fleshly consultings, that your enemy would infuse into your minds; which,
if entertained, how soon may they, who are strong, thereby become weak,
and they who witness freedom be brought again into bondage,
and be again caught in the serpent`'s snares; for he is exceedingly busy within,
as well as without, seeking daily whom he may devour and betray.
Dear lambs, you are in measure acquainted with his subtlety; yes, blessed be the Lord,
who has opened your eyes to see him, his temptations and crafty allurements;
and not only so, but you know how to resist them, and overcome him and his temptations,
through the strength of the Lord, who has called and redeemed you from under his power.

Notwithstanding, my dear friends, let me say unto you,
in the brotherly love and tenderness of my soul,
watch and keep close unto the Lord in your own hearts,
that unto him you may be kept faithful, to the very end.
He will make way for your deliverance,
and plead your righteous cause with his and your adversaries, in his own time and season,
to your joy and their sorrow.
Therefore wholly commit your cause unto the Lord your God,
who watches over you and cares for you, and will never leave you; but will stand by,
and help you in the needful time, even all you whose trust and hope is in him alone.
Dear lambs, in the pure patience and long-suffering of our Captain, Leader, and Example,
that meek One who says,
"`Love enemies,`" possess your souls;--and rest in stillness and peace,
in quietness and contentedness, in the ark of safety,
which the Lord has prepared for his family, to bear them up above the floods,
until the waters abate and the dry land appear.
So the Lord be with you all, and bind you together in his innocent love,
which thinks no evil, therein to serve him with your whole hearts,
and one another with all self-denial; not striving,
except to be meekest and lowest in mind,
that so you may all be tenderly affectioned one towards another,
forgiving and forbearing one another in love,
the strong bearing with the infirmities of the weak; that,
even as dear children of one Father, you may dwell together in peace,
and in pure unity in the spirit of holiness;
that a joy and comfort you may be to each other in the Lord; upon whom, dear lambs,
wait together very diligently, that of his fulness you may all receive;
for he is ready bountifully to minister to all who wait upon him,
that which he sees is fitting for them, even to their daily nourishment, joy, comfort,
and refreshment.

So, in the everlasting love of the tender God of compassion,
does my soul dearly salute you all, who love the Lord uprightly,
and who make mention of his name in sincerity and truth,
and are willing to suffer for the same, whether you be in bonds or out of bonds.

From your friend and companion in the patience and long-suffering of the Lamb, who has,
must, and shall have the victory over all his enemies,
to triumph and reign in dominion eternally.

William Bennit

Norwich Castle, 29th of 7th mo.
1664.
