== Chapter VII. Some Prison Meditations of a Humble Heart

Oh, my soul, be not unmindful of the large mercy and goodness of the Lord,
showed towards you.
Let the sense of what your compassionate God has done for you,
be continually fresh in and upon you;
for he has freely done that for you which none besides him, the Mighty One, could do.
He has brought you out of the horrible pit, and out of the mire and clay,
has set your feet upon a rock which can never be moved,
and thereon establishes your goings; praises, living praises,
be rendered to the Lord your God forever and forevermore.
Remember, oh, my soul, you were once like a poor silly sheep without a shepherd,
wandering upon the barren mountains,
the dry heaths in the wilderness and solitary places, full of trouble and perplexity,
not knowing the way to the fold of rest, oftentimes mourning and weeping alone,
as a dove without her mate; and no eye saw your sorrow but the Lord alone.
When you did eat your bread with weeping, and mingled your drink with tears,
he the compassionate One, heard your secret cries, and knew your desires;
your sighing and groaning entered into his ears; He was moved with pity towards you,
delivered you out of distress, freely reached forth his arm,
brought you out of the wilderness,
and set your feet in the way which has led you to the fold of rest.

Now, oh, my soul, he is become your Shepherd; he oftentimes feeds you,
causes you to lie down in green pastures, leads you by the still waters,
even Shiloh`'s brook, which runs softly; spreads your table in the sight of your enemies,
anoints your head with the oil of gladness, causes your cup to overflow with new wine,
and has brought you to sit under your own vine and fig-tree,
where none shall make you afraid.
The goodness and mercy of the Lord is unutterable, unfathomable, and incomprehensible!
Oh, the height, the depth, the length, and breadth of his love!
When you meditate thereon, oh, my soul, and consider his lovingkindness towards you,
how can the sense thereof but pitch you even upon a stand of admiration.
Surely, when you look back into his works, and consider how much he has wrought in you,
you can see no end of his praises; living praises to the holy righteous Lord God,
be ascribed by you, oh, my soul, forever and forevermore.

As you are kept in the fresh sense and remembrance of the great mercy and unspeakable
compassion which the Lord your God daily manifests unto you,
how can you but abound in love, in pity, in tenderness,
and compassion towards all people;
but especially towards those who are hungering and thirsting after righteousness,
after everlasting rest and happiness.
When joy has come into you, oh, my soul, as a river, and gladness as a mighty stream,
refreshings as showers in the spring, and consolation as dew upon the tender plants;
when you could shout praises and hallelujahs to your God,
even then you remembered the poor and needy,
and thought you heard his cry sounding in your ears, "`Oh, whose condition is like mine?
Is there any so poor, so weak, so foolish, so desolate as I? Oh, my leanness,
my leanness! how long shall it be thus with me?
How long shall my beloved be hid from me, as in the clefts of the rocks,
and as in the secret places of the stairs?
When shall I have a full enjoyment of him?
Where shall I find one who is sensible of my condition, that can sympathize with me,
and that can speak a word in season unto my poor soul!
Oh, is it thus with any as it is with me?`"

Yes, yes, I believe there are many who have been, and now are in your condition.
For though I am indeed but a child,
yet truly I am in some measure sensible of your condition, and can read it by my own;
and willingly would I help you according to my ability.
Oh, I believe I would be a help to all who stand in need of help,
but especially unto you, you poor soul.
What! are you poor?
So am I. Do you eat your bread weeping, and mingle your drink with your tears?
It is so with me when I lack the enjoyment of him whom my soul loves.
Sometimes my beloved seems to be withdrawn; oh, then sorrows take hold on me,
mourning covers me as a garment, and none sees my tears but the Lord;
they are my food and drink, while my enemy says unto me, "`Where is your God?
Do you think he will ever appear again unto you?
Why do you hunger, thirst, cry and pant after him?
Alas! it is in vain for you to wait for him.
Once indeed you had the enjoyment of him;
once you went with the multitude to the house of God, with the voice of joy and praise,
with a multitude that keep holy-day; but you must not look for such a day again.`"
Thus the adversary of my soul endeavours to add sorrow to my sorrow,
and to increase the weight of my burden, that so I might sink and never rise.

But the Lord my God is near to help me,
even in the time when I can scarcely perceive him;
and when I am (as Peter was) ready to sink,
then his invisible arm of mercy is ready to save me;
and a secret hope he preserves alive in me, that he will appear again to my joy.
Hereby some encouragement I feel stirring in me, to wait upon the Lord patiently,
and to trust in him, though I do not see him.
Surely, oh, my soul, he will appear again to your joy,
for you can not be satisfied without his presence; the Lord seeing it is so with you,
that you desire his presence more than all other things,
surely will not cast you off forever, but will appear again to your joy.
Then why are you so much cast down, oh, my soul,
and why are you thus disquieted within me?
Oh, hope in your God, for you shall yet praise him;
the Lord will yet command his lovingkindness in the daytime,
and in the night season his song shall be with you, even praises to the God of your life.

Oh, wait patiently upon the Lord; his compassions fail not towards those who love him.
He will send forth his light and his truth into you again:
it shall bring you to his holy hill, and to his tabernacle;
then shall you go to the altar of God, unto God your exceeding joy.
It is good for you both to hope and quietly wait upon the Lord;
for "`the Lord is good to them that wait for him, to the soul that seeks him.`"
Oh, wait patiently upon him, even as the husbandman, who sows his seed in the earth,
has long patience for it, until he receive the early and the latter rain.
He who is to come will come, and will not tarry, and his reward will be with him,
even fulness of joy, comfort, peace, rest, and sweet satisfaction.
Surely the Lord will never leave you, if you forsake not him.
He may indeed seem to hide his face from you for a time:
but without doubt he will appear again to your comfort.

Oh, my soul, the Lord often hears you saying in secret,
"`What is the glory of the world to me?
What are the favours, friendship, and estimation of the world to me?
What are the vanities and pleasures of the sons and daughters of men to me?
Surely all these things are but as dross and dung to me,
in comparison of the Lord my God, the fountain of everlasting joy and pleasure.
Oh, if I enjoy him fully, I have enough; he is the joy of my heart,
the rejoicing of my spirit, the strength of my reins, the girdle of my loins;
therefore how can I live without him?`"
Oh, my soul, the Lord intends good unto you by all his dealings with you.
If he hide his face from you for a season, it is to let you see how poor, weak, foolish,
dry, and unfruitful you are without him;
that so you being made to feel your own weakness and inability,
may be the more sensible of the need of his supporting power and saving grace,
and rely the more upon him.

Thus you learn to prize the sweet enjoyment of his presence, to cleave unto him,
to be very careful you do not grieve him,
nor do anything that may cause him to withdraw himself from you.
Oh, my soul, you must know how to be abased and how to abound; how to be full,
and how to be empty; how to be rich, and how to be poor;
and in every condition to be content.
The Lord can open, and none can shut; and he can shut and none can open.
He can open the windows of heaven, and shower down abundantly upon you.
He can even make a plenty in your land, cause your store to abound with corn,
and your fats to overflow with new wine.
He can also shut up the windows of heaven for a time, and make a famine in your land;
and you must not say to him (in a murmuring way,) "`Why do you deal thus with me?`"
For indeed he may do what he will, and all his doings are just and righteous:
in all his dealings with you, he, your dear, tender, nursing Father,
intends good unto you.

Oh, my soul, when the fountain opens,
and fills you with plenty of all things needful for you, even then,
dread and fear before the Lord; take heed of being exalted in spirit,
and beware of a wrong liberty and false security,
which may soon steal upon you at such a time, if you do not abide upon the watch,
and drink the draughts of joy in the pure fear and trembling.
Therefore oh, my soul, whatever you enjoy or receive from the Lord,
or do and suffer for him, keep low in heart, meek in mind, and contrite in spirit,
and then you are in a safe condition.
When you appear wise, strong, rich, and full enough,
even then you are in greater danger than when you appear weak, poor,
and empty in your own eyes.
Although you are not then without danger,
but have cause to fear and watch in all conditions.
Oh, my soul, when you appear weak and poor in your own eyes,
even then take heed of distrust and doubting, but hold fast your trust in the Lord;
let your confidence in his name be firm; honour him by believing in him,
and if he slay you yet trust in him, and never leave him; for, alas! where should you go?
he has the words of eternal life, and is worthy to be glorified, magnified, honoured,
and praised, feared, served, loved, and obeyed forever and forevermore.

Oh, my soul, be watchful, that you do not in the least degree seek glory, honour,
and praise to yourself, and to be had in esteem by others;
but wait to feel self wholly baptized into death, and made of no reputation;
take heed that your left hand know not what your right hand does;
do nothing to be seen of men, or whereby to be accounted of by others, but in all you do,
appeal unto Him, who sees in secret, and He will reward you openly.
Seek to be known and manifested only to the pure, unerring witness in all consciences,
and to stand justified and approved by it, and that is enough; no honour, glory,
nor praise, but to God alone.
Oh, strive not for lordship over others, but rather strive to be meek, humble,
contrite in spirit, condescending even to the lowest, and serving the meanest in love;
seeking peace and unity among the brethren, with all self-denial;
bearing with the infirmities of the weak, watching for the good in all,
without respect of persons.
Seek the glory of God alone, the honour of his name,
the exaltation and spreading of his truth.
Seek the good of all, yes, of your greatest enemies and persecutors;
desiring the salvation of all people, but not the destruction of any.
And, oh, my soul! be circumspect and vigilant to walk as becomes the gospel,
that I may be an adorning to the truth of God,
a holy example unto all people wherever I come;
that the blessing of the Lord my God may be poured down upon me yet more and more,
enabling me to become fruitful unto him,
and an instrument in his hand among the sons and daughters of men, to the praise, glory,
and honour of his name.

Oh, my soul, watch and fear before the Lord; keep your eye unto him,
and look not out at others to walk by imitation;
but if you see any (whatever they be accounted) do those
things which the Lord does not allow you to do,
let not their example induce you to do them, but keep close unto the Lord,
and take counsel of him.
Do not judge or justify those things which you have not a true discerning in,
because another judges or justifies them, but rather be passive in such matters;
stand still and wait upon the Lord for a perfect understanding in all things.

Oh, my soul, seek not liberty to the flesh; beware of that counted freedom,
which is indeed bondage, and which has stolen upon many in their latter days.
Endeavour to put off those things, which in their place are said to be lawful,
but which would if indulged in hinder your growth in the eternal Truth.
And, oh, walk wisely before all men, giving no offence to Jew nor Gentile,
nor to the church of God; knowing there is that which is lawful, but not expedient;
there is that which is lawful, but it edifies not.
Therefore forbear what may be forborne,
and yet be not brought under the power of anything below the life;
but seek after those things which make for edification, love, peace, and unity;
for God is the author of peace, and not of confusion, strife, and debate.
Oh, my soul,
you do greatly desire that I might not appear in
the sight of any of the Lord`'s little ones,
to be more than what I really am; by the grace of God I am what I am; and his grace,
which he has freely bestowed upon me, has not been in vain, praises to his name forever.
All flesh is as grass; and what is man?
he is but a vessel, wherein God may appear or disappear as he pleases;
and indeed the Lord is jealous of his glory, and will not give it to another: therefore,
my soul, seek the glory, honour, and praise of God alone,
unto whom only it is due forever and evermore.

If there be some who were once fresh, green, living, and fruitful unto God,
upon whom is now come coldness, deadness, and barrenness,
and whose love and zeal for the Lord is waxed cold; how can you, oh, my soul,
but fear before the Lord, lest the same should happen unto you?

Therefore cleave unto him, look up unto the Holy One,
who dwells in the high and holy place, and with you also,
O my soul! as you are kept humble in heart and contrite in spirit, trembling at his word.
Look not at your own weakness and inability, but keep your eye unto the Lord,
trust in his name, rely upon his arm, and hope in his mercy.
He makes the poor rich, the weak strong, the simple wise.
Wait patiently upon him; look not out at the greatness of others`' measures,
neither look at the smallness of your own,
lest weariness and discouragement should thereby come upon you;
but be contented with your portion; be faithful unto the Lord;
and being faithful in the little, you shall be made ruler over much,
and enter into the joy of your Lord.
Wait upon Him, who has freely given you what you have of him, and he can give you more.

Oh, my soul, surely you had never as of yourself, turned unto the Lord,
had he not of his own free will turned you, and "`after you were turned, you repented,
and after you were instructed, you smote upon your thigh; yes, you were confounded,
because you did bear the reproach of your youth.`"
And after the Lord had turned you in measure to himself,
surely you had not followed him in the strait and narrow way,
through the cross in the self-denial,
had he not drawn you after him by the cords and wooings of his tender love;
surely you had turned back again from the Lord,
had he not preserved and supported you by his own Almighty power.
His grace has been sufficient for you, both in prosperity and adversity,
in the time of trial, and in the hour of temptation.
So let all flesh be silent in you, oh, my soul, the boaster forever excluded,
and the Lord alone honoured and praised, his unspeakable love and free grace admired,
and his holy name feared and obeyed.
What was I, and what was my father`'s house?
I was neither a prophet, nor a prophet`'s son.
What was I, that the King of Glory should cast his eye upon me,
even when I lay as among the pits, that He should hold forth the sceptre unto me,
and that I should find favour in his sight?
Oh, my soul; the Lord has done much for you; he has made crooked things straight,
and laid mountains low before you; he has made a way for you in the wilderness,
and a path through many a thicket; "`He has lopped the bough with terror,
and the high one of stature has been hewn down;
he did cut down the thickets of the forest with iron,
and Lebanon did fall by a mighty one.`"

Oh, how has his love made you willing to bow your neck to the yoke, to take up the cross,
to despise the shame, and to follow the Lamb through trials and tribulations!
Oh, how has his love caused me to cast off other lovers!
He is become my treasure, and my heart is with Him; so that when I am shut up in prison,
if I enjoy him, oh, then days, months, and years may pass over my head,
and time is not thought long, nor sufferings hard, because of the enjoyment of the Lord,
my treasure; his sweet, refreshing presence, makes a prison delightful to me; praises,
pure living praises to my God forever.
He has been with me in six troubles, and in the seventh he has not left me;
he is my buckler, my strength, my rock, my strong tower,
therefore I will not fear the threats of the wicked,
neither regard the cruelty of the ungodly;
through the strength of my God I will not fear,
though the earth be removed and carried into the midst of the sea;
and though the mountains shake with the swelling thereof; though the heathen rage,
the people imagine vain things, and the rulers take counsel against me.
I will not fear what man can do unto me, for the Lord is with me,
and I shall not be moved; He will help me, and that right early.

I am but a child, weak and feeble, yet having had great experience of the love of my God,
and of his tender fatherly care over me,
how can I but confidently hope in and depend upon him, and believe that He,
the mighty one,
will enable me to wade through and endure the trials he is pleased to exercise me with?
He has hitherto, through his love and mercy, caused my trials to work for my good:
he has nine times delivered me out of the hands of unreasonable men,
out of their prisons and holes, where through his enabling me,
I have suffered for his testimony without murmuring against him;
praises unto him forever.
I am willing to wait your season, oh, my God! for you are with me.
Let me never depart from you, and then I know you will not leave me; but will help,
comfort, and quicken me still; you will feed me with bread from heaven, fresh manna,
morning by morning, and give me to drink of the river of your pleasure daily;
you will enable me to stand faithful to you unto the end of my days,
to finish my testimony for you, your name and truth, in this your day, with joy,
lay down my head in peace, and repose in your tender bosom of endless love,
with your dear children forevermore.
Oh! let it be so, you Holy One! to your praise, who are worthy of all glory, honour,
and everlasting thanksgiving, forever and evermore.
Amen.
Hallelujah.

Oh, my soul, you dearly love the whole flock of God,
wherever scattered upon the face of the earth; you greatly desire their prosperity,
even that the Lord may bless them with all spiritual blessings in Christ Jesus.
Oh, the Lord God Almighty keep his sheep and lambs,
whom he has gathered out of the waste, howling wilderness, from the barren mountains,
and led them into the low, green valley,
where the pure refreshing springs of life eternal encompass them about;
the Lord keep them still and quiet, minding their feeding,
and not at all heeding the raging of the sea, nor regarding the unmerciful waves thereof;
which often appear very high, and as if they would overflow the valley,
and drown all who flee not to the mountains for safety: but let not the sheep and lambs,
the little ones fear, nor flee to the hills for refuge; for behold,
the Holy One of Israel is their Shepherd, and He continually watches over them,
and greatly cares for them.
He it is who has given bounds to the sea.
He can let forth the wind and permit a storm, and he can make a calm when he pleases.
Let not Israel fear, for the Lord his God is between him and his enemies,
and fights for him against his adversaries; He will look down upon them in his anger,
and trouble their host; He will take off their chariot wheels,
and will blow in his wrath upon them;
He will get himself a name through the destruction of Zion`'s enemies,
and honour and magnify himself through the deliverance of his chosen, yes,
all nations shall quake before the mighty God of Israel, who is "`glorious in holiness,
fearful in praises, doing wonders.`"

Oh, let Israel honour his God by believing in him,
and depending upon his arm of everlasting strength; and patiently wait upon Him;
for he that is to come will come, and will not tarry; his work is before him,
and his reward is with him, even joy for the mourners in Zion, beauty for ashes,
and freedom from bondage, burdens, and grievous oppressions.
The Lord will thunder from heaven upon your enemies, O Zion,
and will break your adversaries to pieces; He will give strength to your king,
and exalt the horn of his anointed.
"`He shall reign and prosper, and execute judgment and justice in the earth;
in his days Judah shall be saved,
and Israel shall dwell safely,`" then "`shall it be said to Jerusalem, fear not,
and to Zion, let not your hands be slack; the Lord your God in the midst of you,
is mighty; he will save, he will rejoice over you with joy, he will rest in his love,
he will joy over you with singing.`"
Your maker, your husband,
(the God of Hosts is his name,) will extend joy and peace as a mighty stream,
and endless consolations as a river.
For "`as one whom his mother comforts,`" so will the Lord comfort Jerusalem;
in the sense whereof her children shall rejoice,
and their spirits shall praise and sing glory unto Him,
who is Lord and King of heaven and earth, who is worthy of all glory, praise, and honour,
forever and forevermore.
Amen.

O Lord God Almighty, keep all your people retired in your name;
so that whatever you allow to befall their bodies,
their souls may be safely bound up in the bundle of life.
Oh! increase the patience of your people, and strengthen the faith of your chosen;
support the weak, and uphold the little ones, who cannot go alone,
that none of your flock may grow weary; that all yours may stand in the day of trial,
and be kept in the hour of temptation; that they may be borne up under all sufferings,
and in the end come forth as gold seven times refined in the fire,
to shine as stars in the firmament of your power; to declare of your mighty acts,
and sing of your mercies and wonderful doings; to glorify, magnify, honour,
and praise you, you Mighty One, who are from all eternity,
whose throne is established of old, whose sceptre bears sway in righteousness,
and whose kingdom is everlasting.
Glory and Hallelujah to you in the highest, forever and forevermore.
