== Chapter VIII. To Those Who Are Newly Convinced of the Truth

[quote.scripture, , 1 Peter 2:25]
____

For you were as sheep going astray,
but are now returned to the Shepherd and Bishop of your souls.
____

[quote.scripture, , Isaiah 40:11]
____

He shall gather the lambs with his arm, and carry them in his bosom.
____

All you who are newly convinced of the precious truth and way of God,
and have in measure received truth in the love and belief of it,
and who daily give up your hearts to obey the truth,
and to walk in the way of righteousness and path of holiness;
unto you my heart is open in my heavenly Father`'s love;
and happy and blessed of the Lord are you, if you do not faint,
nor grow weary in your minds, nor turn back again, as some have done,
but persevere to the end.
Oh, dear babes! whom the Lord has, by his outstretched arm, brought out of Egypt,
the land of darkness and house of bondage, and whose faces he has set towards Canaan,
the good land of liberty, light, rest, and peace; travel on, you weak ones,
in the strength of the Lord, and drawings of his light, and look not back to Egypt:
remember Lot`'s wife!
Fear not the God of this world, the prince of the power of the airy mind,
even that wicked spirit that once had dominion in and over you,
and kept you bond-slaves in darkness, to sin and corruption; although he,
the enemy of your soul`'s liberty, peace, and rest, may pursue hard after you,
with his whole host of temptations, snares, and allurements, both inward and outward;
and although a sea of troubles, straits, difficulties,
and sufferings may appear in your way, both within and without; and mountains of fears,
doubts, and carnal reasonings on every side;
and also something in you may be ready to murmur and say, "`Oh,
that we had tarried still in Egypt, and not set one step towards Canaan;
for the way is so strait, and the path so narrow, the sufferings so hard,
and the difficulties and dangers so great and various,
that we fear we shall perish by the way, and not get to our desired rest;
therefore let us turn back again before we go any further.`"

Oh, fear not, neither turn back, but stand still from reasoning carnally,
and look not at the straits, trials, dangers, sufferings,
and losses that may appear before you.
Neither look at your own weakness and inability,
nor at the strength and temptation of your enemy; but look up, you little ones,
unto the Lord, and trust in the strength of his arm,
for he is God all-sufficient for you; therefore cast your care upon him,
and he will make a way for you through the sea;
he will make the crooked straight before you, and the rough smooth;
he will throw down the mountains and remove the hills;
he will lead you in way you know not,
and in a path which you have never before trodden in;
he will make hard things easy to the willing and obedient,
who turn not back again to their old lovers, but love truth and righteousness,
and follow on to know the Lord.
All such he will give to drink of the brook by the way,
and feed them with bread from heaven, whereby they shall be refreshed,
and their strength be renewed daily;
in which strength they shall be able to travel on without fainting,
and to run and not be weary, until they come to their desired rest;
and see the travail of their souls,
and be satisfied with the enjoyment of that for which they have travailed.
So the Lord be with you, and keep your eye single unto himself,
that your hearts may be full of light;
that nothing may cause you to stumble and fall into the snares of the enemy,
who has hindered many that once ran well.

Oh, mind and keep to that in your own hearts,
which makes you truly sensible of your particular states and conditions,
and in that sense daily, diligently, and patiently wait upon the Lord,
for the sweet refreshings from his presence, and for the distillings of his heavenly dew;
that so the tender plant of righteousness,
and lily of holiness may grow and spring in all your hearts;
that the little seed of life may become as a great tree,
and every one of you may sit under your own vine, (Christ in you,
the hope of glory) where none shall make you afraid.

And, dear friends, look not out at others, but keep at home in the light, the tent;
Jacob "`shall dwell alone, and shall not be reckoned among the nations.`"
Esau hunts abroad, grows weary and faint,
and then sells his birthright for a mess of pottage.
What if some stumble and fall from the truth?
let not that shake you: truth is the same still and changes not:
and if you see some turn aside from us, into a self-separation from the body of Friends,
and endeavour to draw disciples after them,
let not that cause you to stumble and question the certainty of truth;
neither be drawn away and tossed about like children by them; but keep to the light,
and in it follow the footsteps of the flock.
Follow not the footsteps of the wandering sheep that
have left the flock and are gone astray,
who are like to perish by the devouring beast and enemy of their souls,
except in time they return to the fold.
And if you see some among ourselves setting or keeping
up that thing or practice which is out of the comely,
decent order of the body, and not consistent with truth`'s government,
let not that be an occasion of stumbling in your minds; but be still,
keep your eye single to the Lord, and walk as you have them for an example,
that are over you in the Lord, who fully follow Christ Jesus;
and as for that which is only set up and held up by man, out of truth`'s order,
it will die and pass away, and truth will outlive all.

So unto the Lord, who has called you out of darkness into his marvellous light,
do I commit you; to be preserved unto himself to the end, for "`many are called,
but few chosen;`" "`he that endures to the end shall be saved.`"
